# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

assetic:
    assets:
        d3_sankey_cyclic_js:
            inputs:
                - "@CampaignChainReportAnalyticsCtaTrackingBundle/Resources/public/js/sankey_cyclic.js"
    bundles:
        - CampaignChainReportAnalyticsCtaTrackingBundle