# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_analytics_cta_tracking_per_location_index:
    pattern:  /report/analytics/ctatracking/perlocation/
    defaults: { _controller: CampaignChainReportAnalyticsCtaTrackingBundle:AnalyticsCtaTrackingPerLocation:index }

campaignchain_analytics_cta_tracking_per_location_read:
    pattern:  /report/analytics/ctatracking/perlocation/campaign/{campaignId}/location/{locationId}
    defaults: { _controller: CampaignChainReportAnalyticsCtaTrackingBundle:AnalyticsCtaTrackingPerLocation:read }

campaignchain_analytics_cta_tracking_per_location_data_api:
    pattern:  /api/private/report/analytics/ctatracking/campaign/{campaignId}/location/{locationId}
    defaults: { _controller: CampaignChainReportAnalyticsCtaTrackingBundle:AnalyticsCtaTrackingPerLocation:apiData }